### ISSUE TITLE
please update for latest ffmpeg

### ISSUE THREAD

**Issue by omgbox** [mifi/hls-vod#7]
ffmpeg version 3.4.1-static

please can you update to latest ffmpeg

**Comment by mifi** [comment]
What do you mean? is 3.4.1 not working?

**Comment by omgbox** [comment]
It was not working  , I'm going to try it On a fresh server .

**Comment by omgbox** [comment]
yes its working, but now there is some issue. 

for example, this file http://jell.yfish.us/media/jellyfish-15-mbps-hd-h264.mkv

if you click on preview, you would get this error 

------------------------------------------------------------

/font-awesome-4.4.0/fonts/fontawesome-webfont.woff2?v=4.4.0
/thumbnail/jellyfish-15-mbps-hd-h264.mkv
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at write_ (_http_outgoing.js:625:15)
    at ServerResponse.write (_http_outgoing.js:620:10)
    at Socket.ondata (_stream_readable.js:639:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Socket.Readable.read (_stream_readable.js:475:10)
    at flow (_stream_readable.js:846:34)
    at resume_ (_stream_readable.js:828:3)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

----------------------------------------------------------

another issue i found is, when i click on filename, at the top of the media player, it says, Network Error, but when i click again on the same filename, it starts the transcoder as Active :1 .

hope this helps you.  im testing it on debian 8 64bit

**Comment by mifi** [comment]
I also got the network error. Created a separate issue about it:
#10

I cannot reproduce your second issue, but I removed a possible culprit, so try the newest version
